apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: f4q4xwgds-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-92cf8bbde8.cpmk.p3.openshiftapps.com/rhtap/rhtap-qe:4e046e7ff77eae5624e210d0d889a564c62adcb6@sha256:991f74a3af71fefdab6e9c78c8247b8ec305d225915a41d4a4633a84727b5fc7
          name: container-image
